export const ADD_POLL = 'ADD_POLL';
export const DELETE_POLL = 'DELETE_POLL';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const ANSWER_POLL = 'ANSWER_POLL';
export const GET_ALL_POLLS = 'GET_ALL_POLLS';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const HOST = 'http://localhost:8080/poll/'; // dev
//export const HOST = 'https://voterific.herokuapp.com/polls/'; // prod
